# -*- coding: utf-8 -*-
"""singel_chennel_queque.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-HdIDJXMXXuf8fUGHrWPBHyy3sYsL9fn
"""

from scipy.stats import *

inter_arrival = poisson.rvs( mu = 5.60,size=20 )
inter_arrival[0] = 0



arrival_time = [0]
for i in range(1,20):
  arrival_time.append( inter_arrival[i] + arrival_time[i-1] )
 

import math
import numpy as np
data_expons =  expon.rvs(size=20,loc=5,scale=1/2)
data_test  = data_expons


service_time = [np.round(data_expon) for data_expon in data_expons]



time_service_begin = [0]
customer_wait = [0]
idle_time_server = [0]
time_service_end = []
customer_spend_system = []

value1 = (arrival_time[0] + service_time[0] + customer_wait[0])
time_service_end = [ value1 ]

value2 = (service_time[0] + customer_wait[0])
customer_spend_system = [ value2 ]

count_customer_wait = 0
total_waiting_time = 0

for i in range(1,20):
  
  time_service_begin.append(max(time_service_end[i-1], arrival_time[i]))
  
  if (arrival_time[i] >= time_service_end[i-1 ]):
    customer_wait.append(0)
  else:
    customer_wait.append( time_service_end[i-1] - arrival_time[i] )
    count_customer_wait +=1
    total_waiting_time = total_waiting_time + customer_wait[i]
  
  
  time_service_end.append((arrival_time[i] + service_time[i] + customer_wait[i]))
  customer_spend_system.append((service_time[i] + customer_wait[i]))


  if (arrival_time[i] > time_service_end[i-1 ]):
   idle_time_server.append( arrival_time[i] - time_service_end[i-1] ) 
  else:
    idle_time_server.append(0) 
  
  
  avg_no_of_customer_wait = (count_customer_wait / 20)
  avg_waiting_time = (total_waiting_time / 20)



print("Customer No.","\tInter_Arrival_Time","\tArrival_Time","\tService_Time","\tTime_Service_Begin","\tCustomer_Wait_In_Queue","\tTime_Service_End","\tCustomer_Spend_In_System","\tServer_Idle_Time")

for i in range(20):
  print("\t",i,"\t\t",inter_arrival[i],"\t\t  ",arrival_time[i],"\t\t  ",service_time[i],"\t\t",time_service_begin[i],"\t\t\t",customer_wait[i],"\t\t\t",time_service_end[i],"\t\t\t",customer_spend_system[i],"\t\t\t\t",idle_time_server[i])


print("\n\n\n")
print("total_waiting_time =") 
print(total_waiting_time)
print("avg_no_of_customer_wait  =") 
print(avg_no_of_customer_wait)
print("avg_waiting_time = ") 
print(avg_waiting_time)

